# Generated by Django 3.1.5 on 2021-02-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
